### ISSUE TITLE
Need logging

### ISSUE THREAD

**Issue by ianfoster** [DLHub-Argonne/dlhub_client#4]
It will be important that we integrate logging to record the servables called, the data produced and consumed, and the computational resources consumed. We'll need that for planning, optimization, reporting to funders, and papers.

**Comment by WardLT** [comment]
Were you imagining whether the logging should be on the client or server side?

**Comment by ianfoster** [comment]
Server side is what I was thinking

**Comment by WardLT** [comment]
That's what I figured. I'm going to close this Issue on the client page and tag @ryanchard to add this to his to-do list for the server.

**Comment by ianfoster** [comment]
I was told to add comments to client, at one point. I agree that server makes more sense.

**Comment by ryanchard** [comment]
Ah, I never saw this comment. We currently log invocations, inputs, results, and the execution time. I've been meaning to add resource counters to it as well, but haven't yet included it in the containers.

I'll move the service into this repository.
